export const SIGNIN = 'SIGNIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const ADD_POST = 'ADD_POST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAILURE = 'ADD_POST_FAILURE';

export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';

export const SAVE_INFO = 'SAVE_INFO';
export const SAVE_INFO_SUCCESS = 'SAVE_INFO_SUCCESS';
export const SAVE_INFO_FAILURE = 'SAVE_INFO_FAILURE';

export const GET_INFO = 'GET_INFO';
export const GET_INFO_SUCCESS = 'GET_INFO_SUCCESS';
export const GET_INFO_FAILURE = 'GET_INFO_FAILURE';

export const SEND_EMAIL = 'SEND_EMAIL';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const SEND_EMAIL_FAILURE = 'SEND_EMAIL_FAILURE';

export const IMG_UPLOAD = 'IMG_UPLOAD';
export const IMG_UPLOAD_SUCCESS = 'IMG_UPLOAD_SUCCESS';
export const IMG_UPLOAD_FAILURE = 'IMG_UPLOAD_FAILURE';

export const IMG_RET = 'IMG_RET';
export const IMG_RET_SUCCESS = 'IMG_RET_SUCCESS';
export const IMG_RET_FAILURE = 'IMG_RET_FAILURE';

export const WEATHER_CHK = 'WEATHER_CHK';
export const WEATHER_CHK_SUCCESS = 'WEATHER_CHK_SUCCESS';
export const WEATHER_CHK_FAILURE = 'WEATHER_CHK_FAILURE';

export const LOADER_TRUE = 'LOADER_TRUE';
export const LOADER_FALSE = 'LOADER_FALSE';
